Update main.yml

diff --git a/.github/workflows/main.yml b/.github/workflows/main.yml
--- a/.github/workflows/main.yml
+++ b/.github/workflows/main.yml
@@ -22,7 +22,9 @@ jobs:
         env:
           SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}
         run: |
-          snyk code test 
+          snyk code test --severity-threshold=low || true
+          echo "Failing build if high/critical found..."
+          snyk code test --severity-threshold=critical
           snyk monitor --all-projects
 
       - name: Run Snyk CLI SCA & Monitor
